### ISSUE TITLE
Nombre de archivos/directorios

### ISSUE THREAD

**Issue by kmaxxo** [daibeat/quizz-test#1]
No uses espacios en nombre de archivos y directorios, en web puede ser problemático. 

Lo mismo en cuanto a usar caracteres con acentos, llaves, símbolos...

Si usas nombres en mayúsculas y minúsculas tenlo en cuenta a la hora de escribir las llamadas porque algunos sistemas son case-sensitive.

Te digo esto por el nombre del directorio principal "quizz test".

**Comment by daibeat** [comment]
Ok. Gracias. Lo peor es que lo sé y aún así sigo cometiendo esos errores.
