### ISSUE TITLE
Indicador de página

### ISSUE THREAD

**Issue by kmaxxo** [daibeat/quizz-test#3]
Añadir un indicador paginado (1/n) como ayuda visual al usuario para que sepa cuántas preguntas son y por dónde va.

**Comment by daibeat** [comment]
Tras varios intentos y struggles. He conseguido que funcione el indicador, :*)))) (*=lágrima) XD

**Comment by kmaxxo** [comment]
¡Enhorabuena! así es como se suele hacer.

Sólo un par de sugerencias:
- Definir las variables como let o const
https://github.com/daibeat/quizz-test/blob/main/quizz%20test/js/script.js#L115-L116

- Esto es apreciación personal, cada programador tiene sus manías. La función setPageNumber() en las funciones que hace la acción de ir adelante y atrás. Si le metes en showSlide() sólo te tienes que ocupar de llamarla una vez, por lo que la función showSlide se encargaría de cargar la pregunta y controlar el paginado.

**Comment by daibeat** [comment]
Hecho. Aún tengo duda de cuando usar let o const. Se que let se le puede cambiar el valor y const no....

**Comment by kmaxxo** [comment]
Es un tema de teoría de JavaScript. Es un lenguaje no-tipado, que una definición rápida podría ser que no tienes que decidir qué vas a guardar en una variable (string, number, boolean, array...) o que ni siquiera tengas que declarar la variable previamente para poder usarla. En los últimos standars del lenguaje se está tendiendo a mejorar eso para optimizarlo, por eso se está quedando en desuso declarar las variables de manera genérica con **var nombre_variable** por otros métodos como **let** y **const** que indica que esa variable va a sufrir cambios o es una constante en el código.

En nuestro caso, como son variables que no van a sufrir cambios (estamos hablando de alcance de función) ya que van a ser asignadas un valor y se usará sin ser actualizado, deben ser **const** ambas.

Aunque ahora no te salte ningún error o aviso, cuando uses ReactJS será importante ésto.

**Comment by daibeat** [comment]
ok, lo cambio straight away.

**Comment by kmaxxo** [comment]
Si tienes dudas aún dime y te lo explico con algunos ejemplos!
