### ISSUE TITLE
JSON externo

### ISSUE THREAD

**Issue by kmaxxo** [daibeat/quizz-test#4]
Usar un JSON como archivo externo, no como variable. Esto da una capa diferente al código, de tal forma que podrías actualizar las preguntas sin tocar el fichero de código fuente.

**Comment by daibeat** [comment]
Lo que te comentaba el otro día. He encontrado esto: 
`function loadJSON(callback) {   
    var xobj = new XMLHttpRequest();
    xobj.overrideMimeType("application/json");
    xobj.open('GET', 'data.json', true);
    xobj.onreadystatechange = function () {
      if (xobj.readyState == 4 && xobj.status == "200") {
        callback(JSON.parse(xobj.responseText));
      }
    };
    xobj.send(null);  
  }
 
  function init() {
    loadJSON(function(response) {
     // Parse JSON string into object
       var actual_JSON = JSON.parse(response);
    });
   }`
Ahora me falta saber dónde y cómo ponerlo

**Comment by kmaxxo** [comment]
El problema es que ese código es Asíncrono y te complicará más el desarrollo. Prueba con éste, pero la versión Síncrona:

https://stackoverflow.com/questions/44212154/returning-data-from-ajax-callback-by-javascript/44212244#44212244

Para evitar problemas de leer el archivo local, usa esta URL donde he subido tu JSON:

https://www.json-generator.com/api/json/get/cfJMtaNoqG?indent=2

Aún así no podrás usarlo tal cual, te saltará un error. No te digo nada por el momento, dime si no lo consigues y te doy alguna pista.

**Comment by daibeat** [comment]
Se me carga en la consola.  Pero no se ven las questions. :( Me da este error: 


script.js:27 Uncaught TypeError: myQuestions.forEach is not a function
    at buildQuiz (script.js:27)
    at script.js:166
    at script.js:181

Código aquí:
 
`(function () {
  // Functions
  function buildQuiz() {
    // variable to store the HTML output
    const output = [];

    //External JSON

    function myQuestions(url) {
      var request = new XMLHttpRequest();

      request.overrideMimeType("application/json");
      request.open("GET", url, false);
      request.send();

      if (request.readyState === 4 && request.status === 200)
        return request.responseText;
    }

    // An example using ipify api (An IP Address API)
    var json = myQuestions(
      "https://www.json-generator.com/api/json/get/cfJMtaNoqG?indent=2"
    );
    console.log(json);

    // for each question...
    myQuestions.forEach((currentQuestion, questionNumber) => {
      // variable to store the list of possible answers
      const answers = [];

      // and for each available answer...
      for (letter in currentQuestion.answers) {
        // ...add an HTML radio button
        answers.push(
          `<label>
              <input type="radio" name="question${questionNumber}" value="${letter}">
              ${letter} :
              ${currentQuestion.answers[letter]}
            </label>`
        );
      }

      // add this question and its answers to the output
      output.push(
        `<div class="slide">
                <div class="question"> ${currentQuestion.question} </div>
                <div class="answers"> ${answers.join("")} </div>
                </div>`
      );
    });

    // finally combine our output list into one string of HTML and put it on the page
    quizContainer.innerHTML = output.join("");
  }

  function showResults() {
    // gather answer containers from our quiz
    const answerContainers = quizContainer.querySelectorAll(".answers");

    // keep track of user's answers
    let numCorrect = 0;

    // for each question...
    myQuestions.forEach((currentQuestion, questionNumber) => {
      // find selected answer
      const answerContainer = answerContainers[questionNumber];
      const selector = `input[name=question${questionNumber}]:checked`;
      const userAnswer = (answerContainer.querySelector(selector) || {}).value;

      // if answer is correct
      if (userAnswer === currentQuestion.correctAnswer) {
        // add to the number of correct answers
        numCorrect++;

        // color the answers green
        answerContainers[questionNumber].style.color = "green";
      }
      // if answer is wrong or blank
      else {
        // color the answers red
        answerContainers[questionNumber].style.color = "red";
      }
    });

    // show number of correct answers out of total
    resultsContainer.innerHTML = `${numCorrect} out of ${myQuestions.length}`;

    //TODO show all questions with the right or wrong answers
  }

  function showSlide(n) {
    slides[currentSlide].classList.remove("active-slide");
    slides[n].classList.add("active-slide");
    currentSlide = n;
    if (currentSlide === 0) {
      previousButton.style.display = "none";
    } else {
      previousButton.style.display = "inline-block";
    }
    if (currentSlide === slides.length - 1) {
      nextButton.style.display = "none";
      submitButton.style.display = "inline-block";
    } else {
      nextButton.style.display = "inline-block";
      submitButton.style.display = "none";
    }
    setPageNumber();
  }

  function showNextSlide() {
    showSlide(currentSlide + 1);
  }

  function showPreviousSlide() {
    showSlide(currentSlide - 1);
  }

  //PAGE INDICATOR

  function setPageNumber() {
    const descr = document.getElementById("pagenumber");
    const selectedquestionindex =
      currentSlide + 1; /*because Arrays start counting at 0*/
    descr.innerHTML =
      "Question " + selectedquestionindex + " of " + myQuestions.length;
  }

  //Variables
  const quizContainer = document.getElementById("quiz");
  const resultsContainer = document.getElementById("results");
  const submitButton = document.getElementById("submit");

  // const myQuestions = [

  //   {
  //     question: "Who invented JavaScript?",
  //     answers: {
  //       a: "Douglas Crockford",
  //       b: "Sheryl Sandberg",
  //       c: "Brendan Eich",
  //     },
  //     correctAnswer: "c"
  //   },
  //   {
  //     question: "Which one of these is a JavaScript package manager?",
  //     answers: {
  //       a: "Node.js",
  //       b: "TypeScript",
  //       c: "npm"
  //     },
  //     correctAnswer: "c"
  //   },
  //   {
  //     question: "Which tool can you use to ensure code quality?",
  //     answers: {
  //       a: "Angular",
  //       b: "jQuery",
  //       c: "RequireJS",
  //       d: "ESLint"
  //     },
  //     correctAnswer: "d"
  //   }
  // ];

  // display quiz right away
  buildQuiz();

  // Pagination
  const previousButton = document.getElementById("previous");
  const nextButton = document.getElementById("next");
  const slides = document.querySelectorAll(".slide");
  let currentSlide = 0;

  // Show the first slide
  showSlide(currentSlide);

  // Event listeners
  submitButton.addEventListener("click", showResults);
  previousButton.addEventListener("click", showPreviousSlide);
  nextButton.addEventListener("click", showNextSlide);
})();
`

**Comment by kmaxxo** [comment]
Hola @daibeat 

Aquí te he dejado un ejemplo de cómo lo haría yo:
https://github.com/daibeat/quizz-test/pull/8/files

Tienes varias cosas que limar en tu código, primero mira que estás asignando el resultado de la función a una variable llamada **json**, que es la que lees en el **console.log**, pero no es la que usas en el **forEach** para recorrer su contenido. 

También te aconsejo no llamar a las variables como las funciones, para que no te líes entre qué es cada cosa.

¡Saludos!
JM

**Comment by daibeat** [comment]
Ahora funciona. Tenía que usar JSON.parse, porque forEach() es una function de Array, y al hacerlo JSON sería string. Creo que eso es lo que he entendido.  😄

**Comment by kmaxxo** [comment]
¡¡Enhorabuena!! Efectivamente, lo que te devuelve la respuesta del servidor es una cadena de texto con formato JSON, pero para que sea un objeto JSON real y accesible por el código debes convertirlo con JSON.parse(). 

Podemos darlo por cerrado entonces el issue.
