### ISSUE TITLE
Eliminar errores de la consola

### ISSUE THREAD

**Issue by kmaxxo** [daibeat/quizz-test#7]
Sale un error en consola. Intenta que siempre esté limpio de problemas esa parte.

**Comment by daibeat** [comment]
Fixed. Creo que era el onclick="move()"

**Comment by kmaxxo** [comment]
Ese es uno de ellos, también aparece otro porque hay una llamada a un JS que no existe:

![image](https://user-images.githubusercontent.com/728117/107615947-30d91680-6ca1-11eb-96b0-49971989e80e.png)

¡Elimina esa llamada y ya podemos dar por resuelto éste issue!

JM
